root: true

parserOptions:
  ecmaVersion: 6
  sourceType: module

extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - eslint-config-airbnb-base

env:
  es6: true
  browser: true
  node: true
  mocha: true
